#
#  $Id: Makefile.skel,v 1.2 2007-11-16 23:45:08 debug Exp $
#
#  Makefile for GXemul src/gui
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=DebugConsoleWidget.o EmulationDesignArea.o GXemulWindow.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

