#
#  $Id: Makefile.skel,v 1.1 2006-09-02 05:55:19 debug Exp $
#
#  Makefile for GXemul src/net
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=net.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

