#
#  $Id: Makefile.skel,v 1.4 2006-11-08 01:21:27 debug Exp $
#
#  Makefile for GXemul src/promemul
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=arcbios.o dec_prom.o dreamcast.o dreamcast_scramble.o \
	ps2_bios.o of.o pc_bios.o yamon.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

