#
#  $Id: Makefile.skel,v 1.3 2007-06-17 23:32:20 debug Exp $
#
#  Makefile for GXemul src/useremul
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=useremul.o \
	useremul_freebsd.o useremul_netbsd.o \
	useremul_syscalls.o

all: $(OBJS)
	../make_index.sh

$(OBJS): Makefile

useremul.o: useremul.c

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

