#
#  $Id: Makefile.skel,v 1.2 2007-06-15 00:41:21 debug Exp $
#
#  Makefile for GXemul src/useremul
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=useremul.o \
	useremul_freebsd.o useremul_netbsd.o \
	useremul_syscalls.o

all: $(OBJS)

$(OBJS): Makefile

useremul.o: useremul.c

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

