#
#  $Id: Makefile.skel,v 1.3 2006-05-05 21:28:09 debug Exp $
#
#  Makefile for GXemul src/debugger
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugger.o debugger_gdb.o

all: $(OBJS)

$(OBJS): Makefile

debugger.c: debugger_cmds.c

clean:
	rm -f $(OBJS) *core tmp_*.c

clean_all: clean
	rm -f Makefile

