#
#  $Id: Makefile.skel,v 1.2 2006-03-25 19:55:33 debug Exp $
#
#  Makefile for GXemul src/debugger
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugger.o debugger_gdb.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core tmp_*.c

clean_all: clean
	rm -f Makefile

