#
#  $Id: Makefile.skel,v 1.1 2006-03-23 06:51:48 debug Exp $
#
#  Makefile for GXemul src/debugger
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugger.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core tmp_*.c

clean_all: clean
	rm -f Makefile

